# Generated by Django 4.1.6 on 2023-02-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreker', '0004_alter_movie_slug_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Квентин Тарантино', max_length=100),
        ),
    ]
